### ISSUE TITLE
Error with Inner_distance.py

### ISSUE THREAD

**Issue by HIM72** [vals/RSeQC#1]
Sorry if I am asking a question in the wrong place but I couldn't get a answer by googleing.
I ran the inner_distance.py on my STAR alinged bam file and I get the following error

Traceback (most recent call last):
  File "/bi_tools/rseqc/latest/build/scripts-2.7/inner_distance.py", line 87, in <module>
    main()
  File "/bi_tools/rseqc/latest/build/scripts-2.7/inner_distance.py", line 79, in main
    obj.mRNA_inner_distance(outfile=options.output_prefix,low_bound=options.lower_bound_size,up_bound=options.upper_bound_size,step=options.step_size,refbed=options.ref_gene,sample_size=options.sampleSize, q_cut = options.map_qual)
  File "/bi_tools/python/python2.7/lib/python2.7/site-packages/RSeQC-2.3.9-py2.7-linux-x86_64.egg/qcmodule/SAM.py", line 3380, in mRNA_inner_distance
    exon_bitsets = binned_bitsets_from_list(ref_exons)
  File "/bi_tools/python/python2.7/lib/python2.7/site-packages/bx_python-0.7.1-py2.7-linux-x86_64.egg/bx/bitset_builders.py", line 143, in binned_bitsets_from_list
    last_bitset.set_range( start, end - start )
  File "bitset.pyx", line 212, in bx.bitset.BinnedBitSet.set_range (lib/bx/bitset.c:3155)
  File "bitset.pyx", line 185, in bx.bitset.bb_check_range_count (lib/bx/bitset.c:2669)
IndexError: End (536985336) is larger than the size of this BinnedBitSet (536870912).

Can you help with this index error issue? what can I do to solve this problem?

**Comment by vals** [comment]
I am not the author of RSeQC

Here is the website for RSeQC: http://rseqc.sourceforge.net/

Perhaps try to email one of the contacts.
